ElMassimo/vite_ruby

examples/blog/bin/serve
examples/blog/config/puma.rb
lib/tasks/vite/clobber.rake
lib/vite_rails/helper.rb
test/helper_test.rb

This pull request switches from `rel=preload` to `rel=modulepreload`.
While Firefox still doesn't support `modulepreload`, support is over 70%, and the advantage of parsing ahead of time is too big to pass on.
Since Rails doesn't yet have a helper for `modulepreload`, added a new helper, and as a result preload links can now be used in `5.1`.

Use rel=modulepreload instead of rel=preload and enable early hints

---

docs/guide/index.md
vite_rails/README.md
vite_rails_legacy/CHANGELOG.md
vite_rails_legacy/LICENSE.txt
vite_rails_legacy/README.md
vite_rails_legacy/Rakefile
vite_rails_legacy/lib/tasks/vite.rake
vite_rails_legacy/lib/vite_rails_legacy.rb
vite_rails_legacy/lib/vite_rails_legacy/config.rb
vite_rails_legacy/lib/vite_rails_legacy/engine.rb
vite_rails_legacy/lib/vite_rails_legacy/installation.rb
vite_rails_legacy/lib/vite_rails_legacy/tag_helpers.rb
vite_rails_legacy/lib/vite_rails_legacy/version.rb
vite_rails_legacy/templates/config/rails-vite.json
vite_rails_legacy/templates/entrypoints/application.js
vite_rails_legacy/vite_rails_legacy.gemspec

[vite_rails]: https://github.com/ElMassimo/vite_ruby/tree/main/vite_rails
[vite_ruby]: https://github.com/ElMassimo/vite_ruby/tree/main/vite_ruby
This pull request adds `vite_rails_legacy`, which is [__Vite Rails__][vite_rails], modified to support Rails 4.
I don't want the burden of having to support Rails 4 in the main codebase.
And yet, after extracting [_Vite Ruby_][vite_ruby] the surface area is smaller,
and it was easy to adapt it to work with Rails 4.
This way, people get to use the library in Rails 4, and I get to not worry about
accidentally breaking support with changes that are tested on Rails 5 and onwards.
Running on Rails 4.2

Add Vite Rails Legacy, which targets Rails 4

---

vite-plugin-ruby/package.json

This pull request fixes some broken URLs in `vite-plugin-ruby/package.json`.
Specifically, it changes `ElMasssimo` (3 "s"s) to `ElMassimo` (2 "s"s) and changes the branch name `master` to `main` (since there is no `master` branch and the default branch is `main`).
I noticed this because when [dependabot](https://app.dependabot.com/) created [this PR](https://github.com/davidrunger/david_runger/pull/279), the links in the PR description (pointing [here](https://github.com/ElMasssimo/vite_rails) and [here](https://github.com/ElMasssimo/vite_rails/commits)) were 404ing.
I updated the URLs in `vite-plugin-ruby/package.json` to the appropriate URLs.
N/A

Fix URLs in vite-plugin-ruby package

---

vite-plugin-ruby/example/app/assets/theme.css
vite-plugin-ruby/example/app/frontend/components/HelloWorld.vue
vite-plugin-ruby/example/app/frontend/entrypoints/main.ts
vite-plugin-ruby/example/config/vite.json
vite-plugin-ruby/example/vite.config.ts
vite-plugin-ruby/src/index.ts
vite-plugin-ruby/src/types.ts

This pull request adds any paths in [`watchAdditionalPaths`](https://vite-ruby.netlify.app/config/#watchadditionalpaths) to [`server.watcher`](https://github.com/ElMassimo/vite_ruby/blob/main/vite-plugin-ruby/src/index.ts#L72), which ensures Vite detects changes and performs HMR or reload as needed.
It's useful for projects that import code outside the [`sourceCodeDir`](https://vite-ruby.netlify.app/config/#sourcecodedir).

feat: Add paths in watchAdditionalPaths to configureServer (close #21)

---

Gemfile.lock
test/builder_test.rb
test/commands_test.rb
test/engine_rake_tasks_test.rb
test/manifest_test.rb
test/runner_test.rb
test/test_app/config/application.rb
test/test_helper.rb
vite_ruby/lib/vite_ruby.rb
vite_ruby/lib/vite_ruby/build.rb
vite_ruby/lib/vite_ruby/builder.rb
vite_ruby/lib/vite_ruby/cli/build.rb
vite_ruby/lib/vite_ruby/cli/dev.rb
vite_ruby/lib/vite_ruby/commands.rb
vite_ruby/lib/vite_ruby/dev_server_proxy.rb
vite_ruby/lib/vite_ruby/manifest.rb
vite_ruby/lib/vite_ruby/runner.rb
vite_ruby/vite_ruby.gemspec

This pull request groups together several changes to improve the UX when running the build command.
Each change is independent and is implemented in a separate commit, for future traceability.
- Keep track of last build's result and timestamp which enables better error messages for missing entries.
- Now it's possible to run `bin/vite build --inspect` to start a debugging session.
- Now it's possible to run `bin/vite build --force` to build even if files haven't changed.
- Output from `vite build` is now streamed instead of printed when the command ends, providing better feedback.
- Added a mutex in the manifest to avoid multi-threaded servers from unnecessarily triggering several builds in certain (uncommon) situations when using auto-build.

Improve UX when running build command

---

vite_ruby/lib/vite_ruby.rb

Fixes `#dev_server_running?` failing with an exception in case hostname is not resolveable.
That's, for example, the case when using a dockerized development environment (and not running a vite-dev server at all).
I suggest removing the exception class filter altogether like [Webpacker does](https://github.com/rails/webpacker/blob/da362b8c96a4be5a4af8f8ad886f5dd8451f457f/lib/webpacker/dev_server.rb#L21).

fix: handle getaddrinfo errors when checking dev server

---

vite-plugin-ruby/src/config.ts
vite-plugin-ruby/src/index.ts
vite-plugin-ruby/src/types.ts
vite-plugin-ruby/src/utils.ts

This pull request fixes an issue where a [`server.https`](https://vitejs.dev/config/#server-https) option provided by the user in `vite.config.ts` was being overriden by the values in `config/vite.json`.
While it's important to set `"https": true` in `config/vite.json` to ensure the rack proxy doesn't [disable `https`](https://github.com/ElMassimo/vite_ruby/blob/fix/https/vite_ruby/lib/vite_ruby/dev_server_proxy.rb#L47), options provided by the user should be preserved.

fix: Preserve custom server.https configuration (close #42)

---

test/mounted_app/test/dummy/package.json
test/mounted_app/test/dummy/yarn.lock
vite_ruby/lib/vite_ruby.rb

When run `bundle exec vite install`, still use plugin `1.0` version, i think we should use the latest version.

fix: Update installation to use the latest version of the plugin

---

test/builder_test.rb
test/engine_rake_tasks_test.rb
test/runner_test.rb
test/test_helper.rb
vite_ruby/lib/vite_ruby.rb
vite_ruby/lib/vite_ruby/builder.rb
vite_ruby/lib/vite_ruby/cli/dev.rb
vite_ruby/lib/vite_ruby/cli/install.rb
vite_ruby/lib/vite_ruby/io.rb
vite_ruby/lib/vite_ruby/runner.rb

This pull request addresses a minor UX issue mentioned in https://github.com/ElMassimo/vite_ruby/discussions/72, where running `vite install` on a project without a JS lockfile will fail to install dependencies.
As a result of this change, when no lockfile is present it will now default to `npm` (or the user's [preferred package manager](https://github.com/antfu/ni#config)) and proceed to install the dependencies.
Prior to this change, the output of running `npm install` or `yarn install` was being captured—in cases where the installation takes a long time, it was reasonable for a user to think the command had hung.
After this change, the output will be streamed line by line, which is a nicer experience.
Although `ni` supports an interactive prompt when lockfile detection fails, piping …

fix: Stream output during installation and don't skip installation of npm packages when no lockfile is detected

---

test/manifest_test.rb
vite_ruby/lib/vite_ruby/manifest.rb

This pull request fixes the loading of the Vite client and react refresh preamble when an `asset_host` is defined and the dev server is running.
This was happening because when an asset host is defined and a dev server is running the vite client is loaded twice. Once with the `asset_host` domain and once with the relative path (so the current domain).
Consider the case where all assets are provided by `my-cdn.com`. The Vite client loaded with the `vite_client_tag` tag will be loaded without any subdomain (`/vite-dev/@vite/client`) while the client as fetched from within the code will be loaded from the same domain as the asset itself (in this case `my-cdn.com/vite-dev/@vite/client`).
This results in two vite clients being loaded and a crashing page.
By changing the prefixing method of the …

fix: use asset host if set during development

---

vite-plugin-ruby/src/index.ts

Adjust vite configuration to set HMR host and port.
When running an app that uses multiple subdomains, I was running into an issue where I wanted to run vite listening on localhost, and having app loaded from sub1.app.test and sub2.app.test use vite HMR at localhost:3036. I configured development.host in vite.json which correctly set `ViteRuby.config.host_with_port` to `localhost:3036`, but vite client in the browser was trying to connect to `sub1.app.test:3036`, violating CSP.
This change configures the vite client to use the same HMR config as what we're setting on the server side.

Configure vite HMR host from vite.json development.host

---

vite_rails/templates/entrypoints/application.js

Fixes #154. It adds variable declaration to `import.meta.globEager`, as it seems that `Vite.js` doesn't support `import.meta.globEager` calls without saving them somewhere.

fix: add variable declaration to import.meta.globEager (close #154)

---

test/test_app/public/vite-production/manifest.json
vite_ruby/lib/vite_ruby/manifest.rb

This pull request ensures that the new polyfill name with the `\u0000` character is handled as expected.
This was happening because the entry of the legacy-polyfill name has changed to start with a `\u0000` character to mark it as a virtual entry in vite 2.7.
By changing the lookup to not try to parse the entry name, the `\u0000` character is ignored.
Closes #156

fix: handle new virtual legacy-polyfill name

---

docs/guide/rails.md
test/helper_test.rb
test/test_app/public/vite-production/manifest-assets.json
test/test_app/public/vite-production/manifest.json
vite_rails/lib/vite_rails/tag_helpers.rb
vite_rails_legacy/lib/vite_rails_legacy/tag_helpers.rb

Adds a new `vite_image_tag` helper for `vite_rails`. 
Reduces boilerplate a little bit and makes it slightly easier when switching from Webpacker to Vite (replacing `image_pack_tag`).
Discussion here: https://github.com/ElMassimo/vite_ruby/discussions/108#discussioncomment-1858112
Added a new helper to `ViteRails::TagHelpers`

Add #vite_image_tag to ViteRails::TagHelpers

---

test/dev_server_proxy_test.rb
test/test_app/app/frontend/entrypoints/sassy.scss
vite-plugin-ruby/src/config.ts
vite_ruby/lib/vite_ruby/dev_server_proxy.rb

This pull request adds support for providing an empty `publicOutputDir`.
For a while, the dev server proxy relied on `publicOutputDir` as a "prefix" to [detect requests](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/dev_server_proxy.rb#L53) for the Vite dev server.
Now that Vite has patched bugs related to HMR requests, the proxy can rely on [file existence](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/dev_server_proxy.rb#L55).
Avoid adding slashes manually, or rely on `join` from the Node standard library.

fix: allow providing an empty public output dir (close #161)

---

examples/hanami_bookshelf/apps/web/application.rb
vite_hanami/lib/vite_hanami/installation.rb
vite_rails/lib/vite_rails/installation.rb

Add style-src suggestion to content security policy so JS injected styles work in development
Without this, styles injected via JS into a <style type="text/css"> tag won't work
By adding style-src, styles added this way in development

Add style-src to suggestion Content Security Policy changes

---

vite-plugin-ruby/src/config.ts

Currently if the asset hosts contains a protocol (https://my-cdn.org for example),
the path.join method from node will replace the double forward slash with a single
one. Therefore the final base URL will become something like:
```
https:/my-cdn.org/vite
```
This gives problems if vite has to resolve URLs itself. For example if you have:
```
body {
background-image: url('../background.png')
}
```
will resolve in:
```
body { background-image: url('https:/my-cdn.org/vite/background.png') }
```
which in its turn will call this as a relative path.
See above
The fix removes the path.join method with a simple interpolated string.

fix(vite-plugin-ruby): regression in assetHosts protocol

---

vite_ruby/lib/vite_ruby/cli/install.rb

It removes the `.DS_Store` entry inserted by vite_ruby into `.gitignore`, as it is user-specific and should be added to user's global gitignore.

Remove user-specific entries added to .gitignore

---

test/helper_test.rb
vite_rails/lib/vite_rails/tag_helpers.rb

Fixes [189](https://github.com/ElMassimo/vite_ruby/issues/189)

fix: don't add crossorigin to included stylesheet tags (close #189)

---

docs/src/config/index.md
vite-plugin-ruby/src/index.ts
vite-plugin-ruby/tests/index.spec.ts

This pull request solves the issue discussed in https://github.com/ElMassimo/vite_ruby/discussions/186
Staging mode was inconsistent with production mode
This was happening because the code was checking for `mode === 'production'`, but we need the same settings in all non-dev environments (not sure about CI but I guess?).
Replaced previous `isProduction` with `!isDevelopment`, also added a test but my test game is pretty bad, feel free to rework it

fix: disable emptyOutDir in non-development modes

---

vite_rails/lib/vite_rails/config.rb
vite_rails_legacy/lib/vite_rails_legacy/config.rb
vite_ruby/lib/vite_ruby/config.rb

This pull request fixes #202 by ignoring `asset_host` in Rails when configured with a `Proc`.
Usually, [the asset host will be used as the base](https://github.com/ElMassimo/vite_ruby/blob/main/vite-plugin-ruby/src/config.ts#L108) for Vite, which is a good default, especially when `asset_host` is configured to target a CDN.
Rails allows to use a `Proc` to dynamically configure `asset_host`, allowing to return different values depending on the `source`, the URL of an asset.
Since there's no "right" value to pass to Vite when `asset_host` is a `Proc`, it's better to ignore it, which in most cases would still allow assets to be correctly resolved.
In the few cases where this is not desired, [`assetHost` can be explicitly configured](https://vite-ruby.netlify.app/config/index.html#assethost) …

fix: prevent error when using a proc in asset_host (close #202)

---

docs/src/guide/rails.md
test/helper_test.rb
vite_rails/lib/vite_rails/tag_helpers.rb
vite_rails_legacy/lib/vite_rails_legacy/tag_helpers.rb

Add vite_asset_url helper
Needed url to the asset instead of path
By adding the appropriate tag helper

feat: add vite_asset_url helper

---

vite-plugin-ruby/src/config.ts
vite-plugin-ruby/src/index.ts
vite-plugin-ruby/src/types.ts
vite-plugin-ruby/tests/entrypoints.spec.ts
vite-plugin-ruby/tests/index.spec.ts

This pull request adds support for SSR builds, using an approach based on [this prototype](https://github.com/ElMassimo/inertia-rails-ssr-template/commit/b38ef8eb108cd98dea2aadf7d2fbdac72746297b).
The goal is to support use cases such as [SSR with Inertia](https://github.com/inertiajs/inertia-rails/pull/74), and pave the way for other use cases that can benefit from an SSR build (such as Rails API + Node.js SSR).
By detecting whether the `ssr` flag was set when triggering the build, `vite-plugin-ruby` will set an SSR entrypoint instead, and skip any output options related to fingerprinting the resulting assets.
This is experimental, these initial conventions are subject to change in patch releases:
- The SSR entrypoint should be a `{sourceCodeDir}/ssr/ssr.js` file. TypeScript and JSX are …

feat: add support for SSR builds (experimental)

---

vite_ruby/lib/tasks/vite.rake

This pull request restores the previous behavior where the lack of npm and npx does not cause precompilation to raise.
This behavior changed in https://github.com/ElMassimo/vite_ruby/commit/967fbf52aac5e52e1a059bffda79c7472874775f.
Previously, it was not necessary to have `npm` installed.
By changing the code to fallback on error, environments without `npm` will not get an error. 
Long term a better fix might be making pre-installation of dependencies optional for folks who manage their js dependencies using a tool other than npm.

Catch npm command not found, for folks who install deps with yarn

---

vite_ruby/lib/tasks/vite.rake

The vite_ruby rake file was setting `NPM_CONFIG_PRODUCTION=false`, which is deprecated. In recent versions of npm this causes a warning to be printed to the console.
```
npm WARN config production Use `--omit=dev` instead.
```
Fix by detecting the npm version and using `NPM_CONFIG_INCLUDE=dev` instead of `NPM_CONFIG_PRODUCTION=false` for npm 7+.
Ref: https://docs.npmjs.com/cli/v7/using-npm/config#include
Before:
```
$ bundle exec rake assets:precompile
npm WARN config production Use `--omit=dev` instead.
npm WARN config production Use `--omit=dev` instead.
yarn install v1.22.18
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.08s.
Skipping vite build. Watched files have not changed since the last build at 2022-07-09 13:09:30
```
After:
```
$ bundle exec rake …
```

Fix npm deprecation warning on assets:precompile

---

vite_rails/lib/vite_rails/tag_helpers.rb

In order to inherit all the features of the `javascript_include_tag` it should be used within `vite_client_tag`. Otherwise you won't get CSP support and all other built-in features.
You won't be able to work with `vite_client_tag` in a CSP environment without this change.
Use `javascript_include_tag` instead of `tag.script`

fix: use javascript_include_tag in vite_client_tag

---

vite_rails/lib/tasks/vite.rake
vite_rails/lib/vite_rails/config.rb

This pull request ensures that when using `vite_rails` the parent Rails app is initialized before the config is resolved.
This ensures that it's safe to access Rails config values in `config/vite.rb`, and that settings like `asset_host` are always detected.
This pull request is a follow-up to:
- https://github.com/ElMassimo/vite_ruby/issues/193
The [attempt to fix it](https://github.com/ElMassimo/vite_ruby/commit/72afbc7ab5ca33833e9330954499bcf460fd7669) only solved some situations, but does not work in all cases.
Explicitly requiring the application and initializing it ensures the config is available before running a build

fix: ensure rails app is initialized before inferring config

---

vite_ruby/lib/tasks/vite.rake
vite_ruby/lib/vite_ruby/commands.rb

For Yarn 2+, `YARN_PRODUCTION=false` causes `Usage Error: Unrecognized or legacy configuration settings found: production - run "yarn config -v" to see the list of settings supported in Yarn (in <environment>)`
Because there is no such global configuration for Yarn 2+, at least I have not found any similar on https://yarnpkg.com/configuration/yarnrc, we got the issue
Do not add env to prevent warning message if yarn version is more than `1`

fix: prevent yarn 2+ error in `assets:precompile`

---

docs/src/guide/troubleshooting.md

Discussed in [an issue](https://github.com/ElMassimo/vite_ruby/issues/258) opened the other day.
Safari does not respect the combination of `ETag` and `Cache-Control: no-cache` headers without the use of a cache-busting query string. The `vite_stylesheet_tag` helper does not have this cache-busting query string but if you import the CSS directly into the JS, when it gets split out it works.
Bug in Safari
We are documenting the behavior to help folks who may get stumped by it. In the issue, another option was linked in the comments as a workaround but that option didn't appear in my version of Safari and I wasn't able to work out how to disable cache. The only other option I've found so far is to manually empty the cache between stylesheet changes which is not a great dev experience.
Not …

docs: document bug in safari that caches css and prevents hmr

---

test/builder_test.rb
vite_ruby/lib/vite_ruby/manifest.rb

This pull request changes the behavior of `Manifest#lookup` when [`autoBuild`](https://vite-ruby.netlify.app/config/index.html#autobuild) is enabled.
It will now return `nil` if the last build has failed.
Closes #267.
Previously, `lookup` would continue using the last generated manifest when available.
Although this allows a developer to continue working in the app after breaking the build, in practice most users will either:
- Prefer the app to break if the build fails, as logs for failing builds can be missed easily
- Have the Vite dev server running when making changes, in which case `autoBuild` is not used

fix(BREAKING CHANGE): lookup now returns nil if auto-build fails

---

Gemfile.lock
examples/rails/Rakefile
test/builder_test.rb
test/engine_rake_tasks_test.rb
test/manifest_test.rb
test/runner_test.rb
test/test_helper.rb
vite_ruby/lib/vite_ruby/build.rb
vite_ruby/lib/vite_ruby/builder.rb
vite_ruby/lib/vite_ruby/cli/install.rb
vite_ruby/lib/vite_ruby/io.rb
vite_ruby/lib/vite_ruby/missing_entrypoint_error.rb
vite_ruby/vite_ruby.gemspec

This pull request implements the proposal in #269, to display build errors as part of the `ViteRuby::MissingEntrypointError` error message.
This is a nice improvement in UX, as users could now understand the problem without having to manually trigger a build.
Thanks for the suggestion @jrochkind! 😃

feat: display last build errors in MissingEntrypointError

---

test/builder_test.rb
test/engine_rake_tasks_test.rb
test/test_helper.rb
vite_ruby/lib/vite_ruby/builder.rb
vite_ruby/lib/vite_ruby/cli/install.rb
vite_ruby/lib/vite_ruby/io.rb

The process can fail without output to stderr in some cases, like if it was killed. This is confusing because the build says it failed with no reason why. Now, output the status of the command on any failure.
Before:
```
Building with Vite ⚡️
vite v3.2.2 building for test...
transforming...
Build with Vite failed! ❌
```
Now:
```
Building with Vite ⚡️
vite v3.2.2 building for test...
transforming...
pid 869500 SIGKILL (signal 9)
Build with Vite failed! ❌
```
Closes #292.

feat: output exit code when vite process fails

---

.github/workflows/ruby.yml
test/dev_server_proxy_test.rb
test/helper_test.rb
vite_rails/lib/vite_rails/tag_helpers.rb
vite_ruby/lib/vite_ruby/dev_server_proxy.rb

This pull request makes some changes to ensure CSS filenames such as `jquery.tree.css` are not converted to `jquery.tree` in the `ViteRuby::DevServerProxy`.
Historically, `stylesheet_link_tag` in Rails did not support passing `extname` to `asset_path`, causing it to always append `.css` to any provided filenames.
This is problematic in Vite, because the dev server _can_ serve `file.scss`.
For that reason, the `DevServerProxy` needed to convert that `file.scss.css` to `file.css`.
Since it's very uncommon for CSS files to have two extensions, the naive approach of removing the extra `.css` hasn't been a problem in practice, until #300.
Restricting this patch to files with a known CSS preprocessor extension. The regex is more verbose, but should cause less problems.
In addition, [support for …

fix: avoid removing double extension for non-preprocessor assets

---

Gemfile.lock
vite_ruby/lib/vite_ruby.rb
vite_ruby/lib/vite_ruby/builder.rb

This pull request adds caching to `watched_files_digest`,  using the same technique as in [`dev_server_running?`](https://github.com/ElMassimo/vite_ruby/blame/7f2f9eeada757039b73bf15475bdcae0ce3932b6/vite_ruby/lib/vite_ruby.rb).
The result will be cached for a second, before recalculating.
In development, each `lookup` will call `build`, checking whether files have changed since the last build.
Most of the time, pages have a single `vite_typescript_tag`, doing a single lookup.
However, in pages that link many assets using `vite_asset_path` or `vite_image_path`, calculating the digest each time can be very time consuming.
By caching the result, on a normal request lifecycle the digest will only be calculated once, preventing the performance degradation.

perf: avoid calculating digest on each lookup

---

.eslintrc.js
Gemfile.lock
docs/src/config/index.md
vite-plugin-ruby/default.vite.json
vite-plugin-ruby/src/config.ts
vite-plugin-ruby/src/types.ts
vite_ruby/default.vite.json
vite_ruby/lib/vite_ruby/config.rb
vite_ruby/lib/vite_ruby/manifest.rb

This pull request adds an experimental `skipProxy` setting.
Whether to skip the [dev server proxy](https://vite-ruby.netlify.app/overview.html#in-development), and request assets to the Vite development server directly.
Connecting to Vite directly allows assets to be served using HTTP2 when [`https`](http://localhost:3005/config/index.html#https) is enabled.
Don't enable this option in Rails 6 or earlier if you are using `vite_stylesheet_tag` with assets that don't have a `.css` extension, [or Vite will fail to serve them](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/dev_server_proxy.rb#L41).

feat: add experimental `skipProxy` setting

---

Gemfile.lock
vite_ruby/vite_ruby.gemspec

Hello!
Could we bump `dry-cli` dependency version to `1.0.x`? Looks like no breaking changes from `~0.7`

chore: bump dry-cli version

---

vite_rails/lib/vite_rails/tag_helpers.rb

This allows passing options such as `nonce`, which some browsers require if CSP is set (Firefox).
With CSP set in Rails, Firefox would fail to load the vite client tag without a `nonce` set.
`vite_client_tag` now accepts an `options` hash that is passed to `javascript_include_tag`, much like `vite_javascript_tag`.
Co-authored-by: Wil Hall <wil@wilhall.com>

feat: allow javascript_include_tag options to vite_client_tag

---

vite_ruby/lib/tasks/vite.rake

This pull request closes:
- #342 
Vite Ruby will now try to install dependencies with `yarn` in systems where `npx` is not available.
Given how Rails forced users to rely on `yarn` when using `webpacker`, and to this day ships with a `yarn:install` task, it's not unusual that certain container or buildpacks include `yarn` but not `npm`.
As a result, in those deployment setups `npx` might not be available, for example, in the Heroku Ruby buildpack.

feat: install dependencies with yarn if npx is not available

---

examples/rails/Dockerfile

This pull request addresses two issues found in the examples directory's Rails project.
1. The Node version specified in package.json was set to 16, while the Node version in the Rails Dockerfile was 15.14.0. This inconsistency caused the following error message:
```
vite_1   | yarn install v1.22.19
vite_1   | info No lockfile found.
vite_1   | [1/5] Validating package.json...
vite_1   | error blog@0.1.0: The engine "node" is incompatible with this module. Expected version "16". Got "15.14.0"
vite_1   | warning blog@0.1.0: The engine "pnpm" appears to be invalid.
vite_1   | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
vite_1   | error Found incompatible module.
rails_vite_1 exited with code 1
``` …

chore: update dockerfile for the rails example

---

vite-plugin-ruby/package.json

Using eslint, I'm getting an `import/no-unresolved: Unable to resolve path to module 'vite-plugin-ruby'` when it clearly exists. 
Looking at [this ticket](https://github.com/browserify/resolve/issues/222) I believe that is happening because there is no `main` key in the package.json. Note that this error is not happening with the `vite-rails-plugin`, which does specify the `main` key.
This updates the package.json to include the `main` key.

Add "main" to package.json to fix eslint issues

---

examples/rails/docker-vite.sh
examples/rails/spec/features/admin/home_spec.rb

This pull request fixes error visiting /admin path 'ViteRuby::MissingExecutableError in Administrator::Timer#index'
This was happening because vite binary was not available for the engine (engine uses separate node_modules folder).
By running 'yarn install' within the engine's folder when starting vite container.

Install node modules for engine when starting vite container for the Rails example

---

vite_ruby/lib/tasks/vite.rake

Add an env flag `VITE_RUBY_SKIP_INSTALLING_DEV_DEPENDENCIES`, which lets users skip installing dev dependencies in the `install_dependencies` rake task
Not sure what's the best way to test this, so opening as a draft to ask for advice, and see if anyone else thinks this is useful. For my project `devDependencies` only includes non essential things like storybook and linters, hence why I'd like the option to skip installing them
For projects where dev dependencies only include linters etc, this is a nice way of speeding up the build. Similar to how on legacy yarn you could run `yarn install --production`
Alter the task to optionally add `--omit=dev` to the `npx ci` build command.

Allow skipping dev dependencies on install

---

vite_rails/lib/vite_rails/tag_helpers.rb

Update `vite_preload_tag` to emit one early hint per entrypoint
Avoids error like "too many 1xx informational responses"
I am trying this gem with caddy as reverse proxy
And visiting the deployed website returns 502, log shows "too many 1xx informational responses"
I found this issue is reported https://github.com/caddyserver/caddy/issues/5616
Which is caused by having too many 103 responses sent
Update `vite_preload_tag` to emit one early hint per entrypoint (actually all sources input, but it's mainly used by `vite_javascript_tag`)
N/A

Update `vite_preload_tag` to emit one early hint per entrypoint

---

docs/src/guide/plugins.md

From https://github.com/ElMassimo/stimulus-vite-helpers/pull/12#issue-2048150674,
> The `globEager` function was deprecated as of Vite 3.0 and has been removed in Vite 5.0. This updates the README to use the suggested `glob` function with an eager argument instead.
> 
> https://vitejs.dev/guide/migration#removed-deprecated-apis [vitejs/vite#14118](https://github.com/vitejs/vite/pull/14118)
I noticed that the plugins page was missing that, I was in the process of upgrading vite-ruby and had some hard time because the docs was not being reflected.
Hope this helps others out.
Thanks for this amazing project!

docs: update readme to reflect vite's deprecation of globEager

---

vite_ruby/lib/vite_ruby/config.rb

This ensures building isn't skipped when `.mjs` extension is used for the Vite config file.
Vite 5 deprecated CJS, so unless `"type": "module"` is specified in `package.json` (which requires using `.cjs` extension things like PostCSS config), the only way to avoid the deprecation warning is to rename the config file to `vite.config.mjs`.
https://vitejs.dev/guide/migration.html#deprecate-cjs-node-api
I added `vite.config.mjs` to default watched paths.

Add `vite.config.mjs` to watched paths

---

vite_ruby/lib/vite_ruby/manifest.rb

This pull request specifically targets an issue occurring only when encountering `ViteRuby::MissingEntrypointError`. 
The problem stems from the absence of `require 'ostruct'` in these error scenarios. 
This fix ensures that `require 'ostruct'` is included in the appropriate context, resolving the issue and preventing errors during `ViteRuby::MissingEntrypointError` occurrences.

Fix for "uninitialized constant ViteRuby::Manifest::OpenStruct" Error

---

docs/src/guide/deployment.md
vite_ruby/lib/tasks/vite.rake

We want to use the `assets:precompile` extension but we don't want it to install dependencies. This allows setting `VITE_RUBY_SKIP_ASSETS_PRECOMPILE_INSTALL=true` to skip installation while keeping the rest of the task extensions.
This was happening because dependencies are always installed (`yarn install` / `npx ci`) as part of the `assets:precompile` extension.
Add conditional controlled by `VITE_RUBY_SKIP_ASSETS_PRECOMPILE_INSTALL` to allow for skipping the installation task.

feat: allow skipping dependency install in assets:precompile

---

.github/workflows/crawl.yml
.github/workflows/js.yml
.github/workflows/rubocop.yml

Gets rid of deprecation noise in some of the CI runs.

Update `actions/checkout` to v4 (node 16->20)

---

.github/workflows/ruby.yml

I think this will fix the very bottom (Rails edge run) here - https://github.com/ElMassimo/vite_ruby/actions/runs/9422889978/job/25960116922
Rails after 7.1 has switched to expect the secret_key_base to come from credentials, so the secret_key_base config setting from the dummy apps doesn't get picked up, hence that error. This env var should trigger a dummy value to be used (see note in bottom of https://guides.rubyonrails.org/asset_pipeline.html#local-precompilation)

Use `SECRET_KEY_BASE_DUMMY` feature as placeholder during build

---

.github/workflows/ruby.yml

I see the gemspec still supports some quite old ruby/rails versions ... but seems reasonable to just run non-EOL'd on CI?

Drop EOL ruby from CI config

---

docs/src/guide/troubleshooting.md

Safari had an annoying bug where it will ignore changes to CSS files, breaking the developer's hot-reload experience. The Vite Ruby troubleshooting guide [recommends](https://github.com/ElMassimo/vite_ruby/blob/4433471406e7e4957e13acee5151829b36a8eb60/docs/src/guide/troubleshooting.md#L161) moving CSS into the JS entrypoint as a workaround.
However, in Safari 17.5, the problem is now even worse: the bug now affects JS files as well. That means the previously documented workaround is no longer a solution for the entire scope of Safari HMR issues.
Ultimately, the problem is a known bug in Safari where it aggressively caches JS and CSS files that are marked `rel=preload`.
> If a request is preloaded, Safari will always retrieve it from the cache, regardless of the cache headers for that …

docs: More robust solution to Safari dev cache bug

---

test/mounted_app/test/dummy/config/application.rb
test/test_app/config/application.rb

All non-EOL'd Rails version at this point support a `load_defaults` method which can be used to tell Rails which version defaults to start with.
Some of the rails-version-gemfile test runs currently have deprecations about options that are either changing or going away or whatever, but these can generally be silenced by telling a given version to use it's own defaults, which is what this PR does.
Example of warning: https://github.com/ElMassimo/vite_ruby/actions/runs/9424262054/job/25964175006#step:6:9
The one oddity here (explained with inline comment in the diff) is the behavior of `media: screen`. In versions prior to 7.0, the `media` attribute in stylesheet tags would default to `screen`. That was changed in 7.0 to not be there by default, a behvaior which has a config option to …

Use Rails `load_defaults` for relevant gemfile in test runs

---

test/helper_test.rb

Previously this method was going untested in pre-7.1 rails test executions -- changes to assert what we expect (raise) in that path.

Add `vite_picture_tag` coverage for pre-7.1 test paths

---

test/config_test.rb
test/engine_rake_tasks_test.rb
test/rake_tasks_test.rb
test/test_helper.rb

In rails edge there's a helper in place that looks for tests without assertions and warns - https://github.com/rails/rails/blob/main/activesupport/test/testing/test_without_assertions_test.rb#L20
The rails edge CI runs have such a warning, example: https://github.com/ElMassimo/vite_ruby/actions/runs/9424262054/job/25964175625#step:6:12
This change just renames the method to not start with `test_` to silence that warning.

Rename `test_app_path` -> `path_to_test_app` (avoids minitest warning)

---

vite-plugin-ruby/default.vite.json
vite_ruby/default.vite.json
vite_ruby/lib/vite_ruby/cli/vite.rb
vite_ruby/lib/vite_ruby/runner.rb

This pull request changes the default behavior for executing `vite` to use the package manager instead.
For example, `npx vite` or `yarn vite`.
The [`viteBinPath`](https://vite-ruby.netlify.app/config/index.html#vitebinpath) will still be used if provided.
`npm bin` was removed in `npm 9`.
In addition, unlike what happens in other ecosystems, JS is getting _more_ package managers:
- `npm`
- `pnpm`
- `yarn`
- `bun`

feat: change default execution to use `npx vite` instead

---

docs/src/config/index.md
vite-plugin-ruby/default.vite.json
vite_ruby/default.vite.json
vite_ruby/lib/tasks/vite.rake
vite_ruby/lib/vite_ruby/cli/install.rb
vite_ruby/lib/vite_ruby/cli/upgrade_packages.rb
vite_ruby/lib/vite_ruby/commands.rb
vite_ruby/lib/vite_ruby/config.rb
vite_ruby/lib/vite_ruby/runner.rb

This pull request adds a `package_manager` config option, allowing to explicitly specify which package manager should be used to install JS dependencies and execute Vite.
In addition, it can be provided during installation:
```ruby
bundle exec vite install --with pnpm
```
Finally, it adds experimental support for [bun](https://bun.sh/) now that it's 1.1.
Closes:
- #324

feat: add `package_manager` config option, experimental support for bun

---

vite-plugin-ruby/src/index.ts

Storybook (builder-vite) adds an `iframe.html` entry into the `rollupOptions` when building a static build. I found that `vite-plugin-ruby` is overriding these options meaning that the Storybook build fails.
Storybook builds are failing for projects using `vite-plugin-ruby` or `vite-plugin-rails`.
Build/Rollup options without the spread:
```js
{
emptyOutDir: false,
sourcemap: true,
target: [ 'chrome108', 'edge108', 'firefox109', 'ios15', 'safari15' ],
outDir: '<path-to-project>/storybook-static',
rollupOptions: {
external: [ './sb-preview/runtime.js', /\.\/sb-common-assets\/.*\.woff2/ ],
input: {
'entrypoints/application.ts': '<path-to-project>/app/frontend/entrypoints/application.ts',
'entrypoints/vue.ts': '<path-to-project>/app/frontend/entrypoints/vue.ts'
},
output: {
assetFileNames: …
```

Allow `rollupOptions` set by other plugins to be respected

---

docs/src/config/index.md

This pull request corrects the default value of the `viteBinPath` configuration setting.
The default is incorrectly given for the `viteBinPath` configuration setting after the change merged in #480.
By fixing the default in the documentation, misconfiguration and errors in build and deployment workflows are avoided.

fix documentation for viteBinPath default value

---

.github/workflows/ruby.yml
gemfiles/Gemfile-rails.7.2.x

Update CI to add rails 7.2 to test matrix
Check change log, somehow also checked test matrix, found that rails 7.2 missing
Add it
N/A

Update CI to add rails 7.2 to test matrix

---

.github/workflows/js.yml
.github/workflows/rubocop.yml
.github/workflows/ruby.yml

Update CI to use latest ruby for rubocop, use NodeJS 20.x
Saem as https://github.com/ElMassimo/vite_ruby/pull/503
Just update it

Update CI to use latest ruby for rubocop, use NodeJS 20.x

---

vite-plugin-ruby/src/config.ts

Do not override config.server.origin when the user provides it.
Using Vite-ruby with docker compose has many pitfalls (see #391 but this one cannot be worked around.
Is pretty trivial as you'll see in the code
nope :sweat_smile:

fix: Do not override userConfig.server.origin on skipProxy=true

---

test/helper_test.rb
vite_rails/lib/vite_rails/tag_helpers.rb

When specifying the host and protocol options for a `vite_javascript_tag`, we want the preload tags to also respect those options.
This was causing an issue where the preload tags would not use the CDN specified for the `vite_javascript_tag`.

Respect host and protocol options in vite_preload_tag

---

.github/workflows/ruby.yml
gemfiles/Gemfile-rails.6.1.x

Version 6.1 is EOL as of either the beginning or end of this month, depending what you read. Drop from matrix.
Separately ... are these gemfiles/* files generated by hand, or with a tool?

Drop EOL rails version from CI config

---

vite_ruby/lib/vite_ruby/config.rb

Update the `detect_package_manager` method so that it looks for both Bun lockfile formats. Without this change, Bun setups that use [the new lockfile format](https://bun.sh/docs/install/lockfile#text-based-lockfile) could fail to build, since Vite Ruby would incorrectly think that `npm` was the desired package manager.
Bun is in the process of switching from the binary `bun.lockb` file to a new, text-based `bun.lock` file. 
As of Bun 1.2, the new text-based lockfile is the default. We need to update the `detect_package_manager` to look for both lockfile formats, but we should be able to eventually retire the binary lockfile format.
More info: https://bun.sh/docs/install/lockfile#text-based-lockfile
By looking for the new lockfile format (as well as the old one), the …

Update `detect_package_manager` to look for new Bun lockfile

---

docs/src/guide/deployment.md

This pull request fixes a typo on markdown tag
This was happening because the tag was wrong
By changing the [ ] to ( )

fix: markdown link tag
